In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv("gld_price_data.csv")
df.sample(10)

            Date          SPX         GLD        USO        SLV   EUR/USD
807    9/13/2011  1172.869995  178.539993  34.849998  39.869999  1.368607
612    11/1/2010  1184.380005  131.919998  35.810001  24.070000  1.397507
144    9/23/2008  1188.219971   88.320000  86.129997  13.180000  1.463315
380   10/14/2009  1092.020020  104.180000  38.610001  17.559999  1.495595
206   12/29/2008   869.419983   86.349998  30.920000  10.770000  1.403903
1137    3/4/2013  1525.199951  152.300003  32.400002  27.600000  1.301693
1967   12/6/2016  2212.229980  111.430000  11.290000  15.850000  1.075732
550    7/13/2010  1095.339966  118.360001  34.740002  17.820000  1.274048
263    3/23/2009   822.919983   92.080002  31.780001  13.460000  1.362045
410   11/30/2009  1095.630005  115.639999  39.150002  18.150000  1.503895

In [4]:
df.isnull().sum()

Date       0
SPX        0
GLD        0
USO        0
SLV        0
EUR/USD    0
dtype: int64

In [5]:
df.shape

(2290, 6)

In [6]:
df.describe()

               SPX          GLD          USO          SLV      EUR/USD
count  2290.000000  2290.000000  2290.000000  2290.000000  2290.000000
mean   1654.315776   122.732875    31.842221    20.084997     1.283653
std     519.111540    23.283346    19.523517     7.092566     0.131547
min     676.530029    70.000000     7.960000     8.850000     1.039047
25%    1239.874969   109.725000    14.380000    15.570000     1.171313
50%    1551.434998   120.580002    33.869999    17.268500     1.303297
75%    2073.010070   132.840004    37.827501    22.882500     1.369971
max    2872.870117   184.589996   117.480003    47.259998     1.598798

In [7]:
gold=df.drop("Date",axis=1)
gold.head()

           SPX        GLD        USO     SLV   EUR/USD
0  1447.160034  84.860001  78.470001  15.180  1.471692
1  1447.160034  85.570000  78.370003  15.285  1.474491
2  1411.630005  85.129997  77.309998  15.167  1.475492
3  1416.180054  84.769997  75.500000  15.053  1.468299
4  1390.189941  86.779999  76.059998  15.590  1.557099

In [8]:
correlation=gold.corr()

In [9]:
correlation

              SPX       GLD       USO       SLV   EUR/USD
SPX      1.000000  0.049345 -0.591573 -0.274055 -0.672017
GLD      0.049345  1.000000 -0.186360  0.866632 -0.024375
USO     -0.591573 -0.186360  1.000000  0.167547  0.829317
SLV     -0.274055  0.866632  0.167547  1.000000  0.321631
EUR/USD -0.672017 -0.024375  0.829317  0.321631  1.000000

In [10]:
X=gold.drop("GLD",axis=1)
y=gold["GLD"]
print(X.shape)

(2290, 4)

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model=RandomForestRegressor()
model.fit(X_train,y_train)

RandomForestRegressor()

In [12]:
y_pred=model.predict(X_test)

In [13]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae1=mean_absolute_error(y_pred,y_test)
print(mae1)

1.2059425426200867

In [14]:
mse1=mean_squared_error(y_pred,y_test)
print(mse1)

5.2411774798515935

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model1=LinearRegression()

In [17]:
model1.fit(X_train,y_train)

LinearRegression()

In [19]:
y1_pred=model1.predict(X_test)

In [20]:
mae2=mean_absolute_error(y1_pred,y_test)
print(mae2)

5.6959006442692885

In [22]:
mse2=mean_squared_error(y1_pred,y_test)
print(mse2)

56.165594215006024